-- MySQL Script generated by MySQL Workbench
-- Sat Mar 12 13:56:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SICOV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SICOV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SICOV` DEFAULT CHARACTER SET utf8 ;
USE `SICOV` ;

-- -----------------------------------------------------
-- Table `SICOV`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`municipio` (
  `idmunicipio` INT NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`servicioPublico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`servicioPublico` (
  `idservicioPublico` INT NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`idservicioPublico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`colonia` (
  `idcolonia` INT NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  `codigoPostal` VARCHAR(10) NOT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idcolonia`),
  INDEX `fk_colonia_municipio1_idx` (`municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_colonia_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `SICOV`.`municipio` (`idmunicipio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`comite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`comite` (
  `idcomite` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `colonia_idcolonia` INT NOT NULL,
  PRIMARY KEY (`idcomite`),
  INDEX `fk_comite_colonia1_idx` (`colonia_idcolonia` ASC) VISIBLE,
  CONSTRAINT `fk_comite_colonia1`
    FOREIGN KEY (`colonia_idcolonia`)
    REFERENCES `SICOV`.`colonia` (`idcolonia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `SICOV`.`ciudadano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`ciudadano` (
  `idciudadano` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `fotografia` BLOB NOT NULL,
  `numeroTelefonico` VARCHAR(15) NULL,
  `correoElectronico` VARCHAR(100) NULL,
  `numeroEmpleado` VARCHAR(20) NOT NULL,
  `rol_idrol` INT NOT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idciudadano`),
  INDEX `fk_ciudadano_rol1_idx` (`rol_idrol` ASC) VISIBLE,
  INDEX `fk_ciudadano_municipio1_idx` (`municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_ciudadano_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `SICOV`.`rol` (`idrol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ciudadano_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `SICOV`.`municipio` (`idmunicipio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`comiteVecinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`comiteVecinal` (
  `idcomiteVecinal` INT NOT NULL AUTO_INCREMENT,
  `ciudadano_idciudadano` INT NOT NULL,
  `comite_idcomite` INT NOT NULL,
  `esPresidente` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idcomiteVecinal`),
  INDEX `fk_comiteVecinal_ciudadano1_idx` (`ciudadano_idciudadano` ASC) VISIBLE,
  INDEX `fk_comiteVecinal_comite1_idx` (`comite_idcomite` ASC) VISIBLE,
  CONSTRAINT `fk_comiteVecinal_ciudadano1`
    FOREIGN KEY (`ciudadano_idciudadano`)
    REFERENCES `SICOV`.`ciudadano` (`idciudadano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comiteVecinal_comite1`
    FOREIGN KEY (`comite_idcomite`)
    REFERENCES `SICOV`.`comite` (`idcomite`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`incidencia` (
  `idincidencia` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` TINYINT(2) NOT NULL,
  `fechaRegistro` DATETIME NULL DEFAULT NOW(),
  `costo` DOUBLE NULL DEFAULT 0.0,
  `estaPagado` TINYINT NULL DEFAULT 0,
  `servicioPublico_idserviciosPublico` INT NOT NULL,
  `comiteVecinal_idcomiteVecinal` INT NOT NULL,
  PRIMARY KEY (`idincidencia`),
  INDEX `fk_incidencia_servicioPublico1_idx` (`servicioPublico_idserviciosPublico` ASC) VISIBLE,
  INDEX `fk_incidencia_comiteVecinal1_idx` (`comiteVecinal_idcomiteVecinal` ASC) VISIBLE,
  CONSTRAINT `fk_incidencia_servicioPublico1`
    FOREIGN KEY (`servicioPublico_idserviciosPublico`)
    REFERENCES `SICOV`.`servicioPublico` (`idservicioPublico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_incidencia_comiteVecinal1`
    FOREIGN KEY (`comiteVecinal_idcomiteVecinal`)
    REFERENCES `SICOV`.`comiteVecinal` (`idcomiteVecinal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`comentario` (
  `idcomentario` INT NOT NULL,
  `comentario` VARCHAR(255) NOT NULL,
  `anexo` BLOB NULL,
  `ciudadano_idciudadano` INT NOT NULL,
  `incidencia_idincidencia` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_ciudadano1_idx` (`ciudadano_idciudadano` ASC) VISIBLE,
  INDEX `fk_comentario_incidencia1_idx` (`incidencia_idincidencia` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_ciudadano1`
    FOREIGN KEY (`ciudadano_idciudadano`)
    REFERENCES `SICOV`.`ciudadano` (`idciudadano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentario_incidencia1`
    FOREIGN KEY (`incidencia_idincidencia`)
    REFERENCES `SICOV`.`incidencia` (`idincidencia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`evidencia` (
  `idevidencia` INT NOT NULL AUTO_INCREMENT,
  `evidencia` BLOB NOT NULL,
  `incidencia_idincidencia` INT NOT NULL,
  PRIMARY KEY (`idevidencia`),
  INDEX `fk_evidencia_incidencia1_idx` (`incidencia_idincidencia` ASC) VISIBLE,
  CONSTRAINT `fk_evidencia_incidencia1`
    FOREIGN KEY (`incidencia_idincidencia`)
    REFERENCES `SICOV`.`incidencia` (`idincidencia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
