-- MySQL Script generated by MySQL Workbench
-- Sat Mar 12 13:56:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SICOV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SICOV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SICOV` DEFAULT CHARACTER SET utf8 ;
USE `SICOV` ;

-- -----------------------------------------------------
-- Table `SICOV`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`municipio` (
  `idmunicipio` INT NOT NULL auto_increment,
  `nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`servicioPublico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`servicioPublico` (
  `idservicioPublico` INT NOT NULL auto_increment,
  `nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`idservicioPublico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`colonia` (
  `idcolonia` INT NOT NULL auto_increment,
  `nombre` VARCHAR(65) NOT NULL,
  `codigoPostal` VARCHAR(10) NOT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idcolonia`),
  INDEX `fk_colonia_municipio1_idx` (`municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_colonia_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `SICOV`.`municipio` (`idmunicipio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`comite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`comite` (
  `idcomite` INT NOT NULL auto_increment,
  `nombre` VARCHAR(45) NOT NULL,
  `colonia_idcolonia` INT NOT NULL,
  PRIMARY KEY (`idcomite`),
  INDEX `fk_comite_colonia1_idx` (`colonia_idcolonia` ASC) VISIBLE,
  CONSTRAINT `fk_comite_colonia1`
    FOREIGN KEY (`colonia_idcolonia`)
    REFERENCES `SICOV`.`colonia` (`idcolonia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `SICOV`.`ciudadano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`ciudadano` (
  `idciudadano` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `fotografia` BLOB,
  `numeroTelefonico` VARCHAR(15) NULL,
  `correoElectronico` VARCHAR(100) NULL,
  `numeroEmpleado` VARCHAR(20) NOT NULL,
  `rol_idrol` INT NOT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idciudadano`),
  INDEX `fk_ciudadano_rol1_idx` (`rol_idrol` ASC) VISIBLE,
  INDEX `fk_ciudadano_municipio1_idx` (`municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_ciudadano_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `SICOV`.`rol` (`idrol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ciudadano_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `SICOV`.`municipio` (`idmunicipio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`comiteVecinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`comiteVecinal` (
  `idcomiteVecinal` INT NOT NULL AUTO_INCREMENT,
  `ciudadano_idciudadano` INT NOT NULL,
  `comite_idcomite` INT NOT NULL,
  PRIMARY KEY (`idcomiteVecinal`),
  INDEX `fk_comiteVecinal_ciudadano1_idx` (`ciudadano_idciudadano` ASC) VISIBLE,
  INDEX `fk_comiteVecinal_comite1_idx` (`comite_idcomite` ASC) VISIBLE,
  CONSTRAINT `fk_comiteVecinal_ciudadano1`
    FOREIGN KEY (`ciudadano_idciudadano`)
    REFERENCES `SICOV`.`ciudadano` (`idciudadano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comiteVecinal_comite1`
    FOREIGN KEY (`comite_idcomite`)
    REFERENCES `SICOV`.`comite` (`idcomite`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`incidencia` (
  `idincidencia` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` TINYINT(2) NOT NULL,
  `fechaRegistro` DATETIME NULL DEFAULT NOW(),
  `costo` DOUBLE NULL DEFAULT 0.0,
  `estaPagado` TINYINT NULL DEFAULT 0,
  `servicioPublico_idserviciosPublico` INT NOT NULL,
  `comiteVecinal_idcomiteVecinal` INT NOT NULL,
  PRIMARY KEY (`idincidencia`),
  INDEX `fk_incidencia_servicioPublico1_idx` (`servicioPublico_idserviciosPublico` ASC) VISIBLE,
  INDEX `fk_incidencia_comiteVecinal1_idx` (`comiteVecinal_idcomiteVecinal` ASC) VISIBLE,
  CONSTRAINT `fk_incidencia_servicioPublico1`
    FOREIGN KEY (`servicioPublico_idserviciosPublico`)
    REFERENCES `SICOV`.`servicioPublico` (`idservicioPublico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_incidencia_comiteVecinal1`
    FOREIGN KEY (`comiteVecinal_idcomiteVecinal`)
    REFERENCES `SICOV`.`comiteVecinal` (`idcomiteVecinal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`comentario` (
  `idcomentario` INT NOT NULL auto_increment,
  `comentario` VARCHAR(255) NOT NULL,
  `anexo` BLOB NULL,
  `ciudadano_idciudadano` INT NOT NULL,
  `incidencia_idincidencia` INT NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `fk_comentario_ciudadano1_idx` (`ciudadano_idciudadano` ASC) VISIBLE,
  INDEX `fk_comentario_incidencia1_idx` (`incidencia_idincidencia` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_ciudadano1`
    FOREIGN KEY (`ciudadano_idciudadano`)
    REFERENCES `SICOV`.`ciudadano` (`idciudadano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentario_incidencia1`
    FOREIGN KEY (`incidencia_idincidencia`)
    REFERENCES `SICOV`.`incidencia` (`idincidencia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SICOV`.`evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`evidencia` (
  `idevidencia` INT NOT NULL AUTO_INCREMENT,
  `evidencia` BLOB NOT NULL,
  `incidencia_idincidencia` INT NOT NULL,
  PRIMARY KEY (`idevidencia`),
  INDEX `fk_evidencia_incidencia1_idx` (`incidencia_idincidencia` ASC) VISIBLE,
  CONSTRAINT `fk_evidencia_incidencia1`
    FOREIGN KEY (`incidencia_idincidencia`)
    REFERENCES `SICOV`.`incidencia` (`idincidencia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SICOV`.`bitacora_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`bitacora_actividad` (
  `idBitacoraActividad` INT NOT NULL AUTO_INCREMENT,
  `operacion` VARCHAR(10) DEFAULT NULL,
  `usuario` VARCHAR(40) DEFAULT NULL,
  `host` VARCHAR(30) NOT NULL,
  `fecha` DATETIME DEFAULT NULL,
  `tabla` VARCHAR(40) NOT NULL,
  `datos` VARCHAR(400) DEFAULT NULL,
  PRIMARY KEY (`idBitacoraActividad`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SICOV`.`bitacora_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SICOV`.`bitacora_login` (
  `idBitacoraLogin` INT NOT NULL AUTO_INCREMENT,
  `fechaAcceso` DATETIME NOT NULL,
  `correoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBitacoraLogin`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- TRIGGERS Bitacora Actividades
-- -----------------------------------------------------

DROP TRIGGER IF EXISTS `bitacoraMunicipioIns`;
DELIMITER //
  CREATE TRIGGER `bitacoraMunicipioIns` AFTER INSERT ON `municipio`
  FOR EACH ROW BEGIN
    INSERT INTO bitacora_actividad(host, usuario, operacion, fecha, tabla, datos)
    VALUES (SUBSTRING(USER(), (INSTR(USER(),'@')+1)), SUBSTRING(USER(),1,(instr(user(),'@')-1)), "INSERTAR", NOW(), 'MUNICIPIO',
		CONCAT('Nombre del municipio: ',new.nombre)
    );
    END
//

DROP TRIGGER IF EXISTS `bitacoraColoniaIns`;
DELIMITER //
  CREATE TRIGGER `bitacoraColoniaIns` AFTER INSERT ON `colonia`
  FOR EACH ROW BEGIN
    INSERT INTO bitacora_actividad(host, usuario, operacion, fecha, tabla, datos)
    VALUES (SUBSTRING(USER(), (INSTR(USER(),'@')+1)), SUBSTRING(USER(),1,(instr(user(),'@')-1)), "INSERTAR", NOW(), 'COLONIA',
		CONCAT('Nombre de la colonia: ',new.nombre,',', ' Codigo Postal: ',new.codigoPostal)
    );
    END
//

DROP TRIGGER IF EXISTS `bitacoraRolIns`;
DELIMITER //
  CREATE TRIGGER `bitacoraRolIns` AFTER INSERT ON `rol`
  FOR EACH ROW BEGIN
    INSERT INTO bitacora_actividad(host, usuario, operacion, fecha, tabla, datos)
    VALUES (SUBSTRING(USER(), (INSTR(USER(),'@')+1)), SUBSTRING(USER(),1,(instr(user(),'@')-1)), "INSERTAR", NOW(), 'ROL',
		CONCAT('Nombre del rol: ',new.nombre)
    );
    END
//

DROP TRIGGER IF EXISTS `bitacoraServicioPublicoIns`;
DELIMITER //
  CREATE TRIGGER `bitacoraServicioPublicoIns` AFTER INSERT ON `servicioPublico`
  FOR EACH ROW BEGIN
    INSERT INTO bitacora_actividad(host, usuario, operacion, fecha, tabla, datos)
    VALUES (SUBSTRING(USER(), (INSTR(USER(),'@')+1)), SUBSTRING(USER(),1,(instr(user(),'@')-1)), "INSERTAR", NOW(), 'SERVICIO PUBLICO',
		CONCAT('Nombre del servicio publico: ',new.nombre)
    );
    END
//

-- -----------------------------------------------------
-- Registros
-- -----------------------------------------------------

/*Tabla: Municipio*/
INSERT INTO `sicov`.`municipio` (`idmunicipio`, `nombre`) VALUES ('1','Emiliano Zapata');

/*Tabla: Colonia*/
INSERT INTO `sicov`.`colonia` (`idcolonia`, `nombre`, `codigoPostal`, `municipio_idmunicipio`) VALUES ('1','Tezoyuca', '62767', '1');

/*Tabla: Comite*/
INSERT INTO `sicov`.`comite` (`idcomite`, `nombre`, `colonia_idcolonia`) VALUES ('1','Comite Vecinal Tezoyuca', '1');

/*Tabla: Rol*/
INSERT INTO `sicov`.`rol` (`idrol`, `nombre`) VALUES ('1','Administrador');
INSERT INTO `sicov`.`rol` (`idrol`, `nombre`) VALUES ('2','Presidente de Comité');
INSERT INTO `sicov`.`rol` (`idrol`, `nombre`) VALUES ('3','Enlace');
INSERT INTO `sicov`.`rol` (`idrol`, `nombre`) VALUES ('4','Ciudadano');

/*Tabla: Ciudadano*/
INSERT INTO `sicov`.`ciudadano` (`idciudadano`, `nombre`, `primerApellido`, `segundoApellido`, 
				`numeroTelefonico`, `correoElectronico`, `numeroEmpleado`, `rol_idrol`,`municipio_idmunicipio`) 
VALUES ('1', 'Jean', 'Hernandez', 'Gonzalez', '7776023979', 'jeanhernandez@utez.edu.mx', '1234', '1', '1');

/*Tabla: Comite Vecinal*/
INSERT INTO `sicov`.`comiteVecinal` (`idcomiteVecinal`, `ciudadano_idciudadano`, `comite_idcomite`) 
VALUES ('1','1','1');

/*Tabla: Servicio Publico*/
INSERT INTO `sicov`.`servicioPublico` (`idservicioPublico`, `nombre`) VALUES ('1', 'Dreanje');
INSERT INTO `sicov`.`servicioPublico` (`idservicioPublico`, `nombre`) VALUES ('2', 'Alumbrado Público');
INSERT INTO `sicov`.`servicioPublico` (`idservicioPublico`, `nombre`) VALUES ('3', 'Agua Potable');
INSERT INTO `sicov`.`servicioPublico` (`idservicioPublico`, `nombre`) VALUES ('4', 'Seguridad');
INSERT INTO `sicov`.`servicioPublico` (`idservicioPublico`, `nombre`) VALUES ('5', 'Recoleccion de Basura');

/*Tabla: Incidencia*/
INSERT INTO `sicov`.`incidencia` (`idincidencia`, `descripcion`, `estado`, `fechaRegistro`, `costo`, `estaPagado`, 
								`servicioPublico_idServiciosPublico`, `comiteVecinal_idcomiteVecinal`) 
VALUES ('1', 'Esta es la descripción de la incidencia', '1', now(), '100', '0', '1', '1');


